### ISSUE TITLE
Nicks should be reversed if they appear in a quote/fact

### ISSUE THREAD

**Issue by aptmac** [oldterns/VileBot#102]
Similar to how this is done for `!speak`, it'd be nice to reverse the nicks of people who are currently online when displaying quotes or facts.

Example:

Doing something like

`!quotesearch almac quick`

will ping three people because

> almac once said, "quick, jafeer say something quoteable with yzhang in it"

**Comment by justinmcook** [comment]
Fixed by #114 / #115
