### ISSUE TITLE
remove video clues from jeopardy

### ISSUE THREAD

**Issue by itpun** [oldterns/VileBot#59]
they seem to be tagged with [video clue] so should be easy to filter

**Comment by amisevsk** [comment]
From the api [we're using](http://jservice.io/): 

>Please mark a clue as invalid when the needed information is not present in the clue. This sometimes happens when clues rely on images or sounds to be answered. When useing jService, you may want to check the invalid_count attribute on clues before using them.

We could try that first -- it should be a really simple modification to `Trivia.java`

**Comment by itpun** [comment]
thanks @amisevsk i'll try that first. From the API it looks like it just returns either a 1 or 0 depending if it is invalid or not.

**Comment by emmettu** [comment]
Filtering out the invalid questions would be a good idea. Unfortunately, if I remember correctly, invalid clues don't actually get marked invalid very often, regardless it couldn't hurt unless people mark valid questions as invalid.
