### ISSUE TITLE
no !ttc or !weather

### ISSUE THREAD

**Issue by onyiny-ang** [oldterns/VileBot#77]
Recently Vilebot has stopped responding to !weather and !ttc commands. I haven't had much time to look into it but suspect it could have something to do with running Vilebot over vpn as opposed to on the internal network. It might be worth considering an alternative way of coding these commands if it depends on the internal network somehow.

**Comment by onyiny-ang** [comment]
Update: Vilebot is now running in a vm on the internal network so the issue isn't related to running Vilebot over VPN as I previously suspected.

**Comment by onyiny-ang** [comment]
Weather fixed by #81

**Comment by emmettu** [comment]
I would imagine the !ttc issue is due to the ttc changing the html that the handler scrapes causing it to fail.

No guarantees, but that would be my first guess.

**Comment by onyiny-ang** [comment]
I actually think !ttc is working again since Vilebot was moved to the vm. I'm not sure what the problem was before but I'm going to call this closed for now.
