### ISSUE TITLE
[FeatureRequest] Create a markov-chain generator for vilebot

### ISSUE THREAD

**Issue by thescouser89** [oldterns/VileBot#8]
Vilebot will feed on what people has said before in channels to generate phrases using a markov-chain.

**Comment by emmettu** [comment]
Whoa forgot to close this issue.

**Comment by lberk** [comment]
re-opening, we want the markov-chains!!!

**Comment by emmettu** [comment]
:+1:  VileBot has markov chains now. They can be accessed with the !speak command. I just haven't pulled them from my fork yet.

**Comment by lberk** [comment]
If it's not in the public repo it doesn't exist, feel free to close the issue ones it's been merged.

**Comment by emmettu** [comment]
Markov features have been merged into oldterns/VileBot.
