### ISSUE TITLE
Issue with ++/--ing nicks with special characters

### ISSUE THREAD

**Issue by Christopher-Chianelli** [oldterns/VileBot#87]
I discovered this issue when implementing Karmalytics. If a nick has a "|" or other special characters in it, the karma goes to "nick|status++" instead of "nick". Expected: karma goes to "nick" instead.

**Comment by Josh-Matsuoka** [comment]
This is related to https://github.com/oldterns/VileBot/issues/50

**Comment by Christopher-Chianelli** [comment]
Fixed by #123
